### ISSUE TITLE
Won't compile on current Ubuntu (22.04) or OS X (14.2.1)

### ISSUE THREAD

**Issue by stevesalo** [ragnarlonn/dhcptool#2]
Seems to be a compatibility issue with 'struct ip' in the included current libraries. Adding #include <netinet/ip.h> to dhcptool.c allows for a successful compile (still with warnings). However, it works again :)

**Comment by ragnarlonn** [comment]
Hi @stevesalo and thanks for the report!  I think I've fixed these issues now. I checked in a new branch called "09c" with the changes. If you want to test it it'd be great - if everything seems to work for you I'll merge it into the master branch.

**Comment by stevesalo** [comment]
Compiles and runs great on OS X with 09c.

Excellent and thank you very much!

**Comment by ragnarlonn** [comment]
@stevesalo Thanks Steve, I merged it now!
